listening-port=3478
fingerprint
realm=qiuhua.ying-guang.com
server-name=qiuhua.ying-guang.com
lt-cred-mech
user=webbot:webbot_turn_20260517
no-cli
no-tls
no-dtls
listening-ip=10.0.0.10
relay-ip=10.0.0.10
external-ip=182.43.86.126/10.0.0.10
min-port=49160
max-port=49200
pidfile=/var/run/turnserver.pid
log-file=/var/log/turnserver.log
simple-log
verbose
